### PR TITLE
Final

### PR DESCRIPTION
**Pull request by anshrusia200**
All required changes done and PPT added

### CODE REVIEW

**Comment by anshrusia200** [comment]
Pliz squash commits in this PR

**Review by varunKT001 — COMMENTED** [review]
@anshrusia200 
I had told you to write all the attributes on the `Entity sets and relationship set` section, but still you haven't amended those changes 🙂.  I'm merging this one due to lack of time otherwise I was not willing to 🙂. Also, I think the changes you have done should not have taken this much time 🙁. 

Please try to accomodate all the changes told from next time 👍

**Review by varunKT001 — COMMENTED** [review]
Please do one last change 🙂
Also, push the `.pdf` file of the presentation because there are some font-related issues with the `.pptx` file.

**Comment by anshrusia200** [comment]
I have done all required changes. Also what is the use of adding all the attributes of entity and relationship sets , they are already in the schema and tables. I have highlighted all the relationship sets and their type. Also I verified this with our group member shubhajeet pradhan and he said that it was fine. 
I don't understand what changes you were expecting but the link to the report is given and since it should not take much time according to you so i request you to please make changes by yourself  🙂.

**Comment by anshrusia200** [comment]
@varunKT001 
I have done all required changes. Also what is the use of adding all the attributes of entity and relationship sets , they are already in the schema and tables. I have highlighted all the relationship sets and their type. Also I verified this with our group member shubhajeet pradhan and he said that it was fine.
I don't understand what changes you were expecting but the link to the report is given and since it should not take much time according to you so i request you to please make changes by yourself 🙂.

**Comment by anshrusia200** [comment]
Sorry I cant add any more files as I am asleep now🙂.

**Comment by varunKT001** [comment]
> @varunKT001 I have done all required changes. Also what is the use of adding all the attributes of entity and relationship sets , they are already in the schema and tables. I have highlighted all the relationship sets and their type. Also I verified this with our group member shubhajeet pradhan and he said that it was fine. I don't understand what changes you were expecting but the link to the report is given and since it should not take much time according to you so i request you to please make changes by yourself 🙂.

@anshrusia200 Fine
I could have done the whole report, but no problem. We will make all the required changes. Also no need to add more files, we will do that too 🙂 you can sleep 👍 

Good Night 👋

**Comment by shubhajeet1207** [comment]
@anshrusia200 We don't have enough time for changing the report. Kindly do this by tonight and if you do so, then this will be very helpful for us in finalizing our project.

**Pull request merged**
